# -*- snakemake -*-
from os.path import join
from snakemake_rules import SNAKEMAKE_RULES_PATH
from snakemakelib_workflows import SNAKEMAKELIB_WORKFLOWS_PATH

workdir: join(SNAKEMAKELIB_WORKFLOWS_PATH, "scrnaseq/tests")

configfile: "config.yaml"

include: join(SNAKEMAKELIB_WORKFLOWS_PATH, "scrnaseq/scrnaseq.workflow")

